import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Providers from "./components/Providers";
import Navbaruser from "./components/Navbar/Navbaruser";
import ReduxProvider from "./components/ReduxProvider";
import { store } from "@/store/store";
import { ToastContainer } from "react-toastify";

const ralewayfont = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" data-theme="light">
      <body className={`${ralewayfont.variable} h-full antialiased`}>
        <SessionProvider session={session}>
          <Providers>
            <ReduxProvider>
              <main className="bg-gray-50">{children}</main>
            </ReduxProvider>
          </Providers>
        </SessionProvider>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
